language: python

# Use container-based infrastructure
sudo: false

python:
 - pypy
 - pypy3
 - 2.7
 - 3.5
 - 2.6
 - 3.3
 - 3.4

install:
 - python setup.py install
 - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

script:
 - coverage run --include=warnaserror.py -m nose -vx tests/test_*.py

after_success:
    # Report coverage and send to coveralls.io
  - pip install coveralls
  - coverage report
  - coveralls

after_script:
 - pip install pep8 pyflakes
 - pyflakes . | tee >(wc -l)
 - pep8 --statistics --count .

matrix:
  fast_finish: true
